name = "FITMathMinimal"
license = "MIT"
licenselink = "https://github.com/FITMath/FITMathMinimal/blob/master/LICENSE.md"
description = "Theme for pages powered by Hugo"
homepage = "https://github.com/FITMath/FITMathMinimal"
min_version = "0.24.1"

[author]
  name = "Jonathan Goldfarb"
  homepage = "https://jgoldfar.github.io/"
